#!/usr/bin/env zsh
echo 'INSTALLING gcc AND STUFF'
curl https://github.com/downloads/kennethreitz/osx-gcc-installer/GCC-10.6.pkg > GCC-10.6.pkg
open GCC-10.6.pkg

echo 'INSTALLING RVM'
bash < <(curl -s https://rvm.beginrescueend.com/install/rvm)
echo 'INSTALLING HOMEBREW'
/usr/bin/ruby -e "$(curl -fsSL https://raw.github.com/gist/323731)"

echo 'INSTALLING: ack, zsh, irssi, etc'
brew install ack
brew install zsh
brew install hub
brew install irssi
brew install tmux

echo 'INSTALLING VIM 7.3'
brew install https://raw.github.com/adamv/homebrew-alt/master/duplicates/vim.rb
