#!/usr/bin/env bash
DEVICE=/sys/class/leds/smc::kbd_backlight/brightness
BACKLIGHT="$(cat $DEVICE)"
INCREMENT=15

if [ $UID -ne 0 ]; then
  echo "Please run this program as superuser"
  sudo $0 $*
exit 0
fi

SET_VALUE=0
case $1 in

  up)
    TOTAL=`expr $BACKLIGHT + $INCREMENT`
    if [ $TOTAL -gt "255" ]; then
      exit 1
    fi
    SET_VALUE=1
    ;;
  down)
    TOTAL=`expr $BACKLIGHT - $INCREMENT`
    if [ $TOTAL -lt "0" ]; then
      exit 1
    fi
    SET_VALUE=1
    ;;
  total)
    TEMP_VALUE=$BACKLIGHT
    while [ $TEMP_VALUE -lt "255" ]; do
      TEMP_VALUE=`expr $TEMP_VALUE + 1`
      if [ $TEMP_VALUE -gt "255" ]; then TEMP_VALUE=255; fi
      echo $TEMP_VALUE > $DEVICE
    done
    ;;
  off)
    TEMP_VALUE=$BACKLIGHT
    while [ $TEMP_VALUE -gt "0" ]; do
      TEMP_VALUE=`expr $TEMP_VALUE - 1`
      if [ $TEMP_VALUE -lt "0" ]; then TEMP_VALUE=0; fi
      echo $TEMP_VALUE > $DEVICE
    done
    ;;
  *)
    echo "Use: $(basename $0) up|down|total|off"
    ;;
esac

if [ $SET_VALUE -eq "1" ]; then
  echo $TOTAL > $DEVICE
fi
