#!/usr/bin/env ruby
# Desc:  nicer output for t ( https://github.com/sferik/t )
# Usage: pipe your timeline/replies/user stream with -c (CSV) option
# Example:
#   t stream timeline -c | ruby better_t
#
# Screenshot: http://cl.ly/image/1t122a2P1q3H
# vi: ft=ruby
require 'csv'
require 'colorize'

username_r = /(@[a-zA-Z0-9_]+)/

ARGF.each_line do |line|
  begin
  id, time, user, status = CSV.parse(line).first
  rescue
    id, time, user, *status = line.split(',')
    status = status.join(" ")
  end

  status.gsub!(username_r) { |s| s.colorize(:red) }
  status.sub!('RT', 'RT'.colorize(:blue))   if status.start_with? 'RT'
  status = "#{'r'.colorize(:green)} #{status}" if status.start_with? '@'

  body = ""
  body << "\n"
  body << status
  body << "\n"
  body << "@#{user}".colorize(:red)
  body << " / "
  body << "#{id.colorize(:yellow)} / #{time.colorize(:green)}"
  puts body

end
