#!/usr/bin/env bash
if [ "$*" = "" ] ; then
  echo "Override env file with ENV_FILE var" >&2
  exit 1
fi
envFile=${ENV_FILE:-.env}
echo "Using $envFile" >/dev/stderr
ENV_STR=$(cat $envFile | grep -v "^#" | sed "s/\s/_/g" | tr "\n" " ")
env $ENV_STR bundle exec  $*
