#!/usr/bin/env bash
if [ "$*" = "" ] ; then
  echo "Override env file with ENV_FILE var" > /dev/stderr
  exit 1
fi

readonly envFile=${ENV_FILE:-.env}

echo "Using $envFile" > /dev/stderr

readonly envStr=$(grep -v "^#" $envFile | sed "s/\s/_/g" | tr "\n" " ")
env $envStr bundle exec  $*
