#!/usr/bin/env bash
# convert https gist links into git links
#from:  https://gist.github.com/user/someid
#to:    git@gist.github.com:someid.git

if [[ -z "$1$2" ]] || [[ $1 = "-h" ]] ; then
  echo 'usage "clone-gist <from> <to>"'
  exit 0
fi

url=$1
name=$2
git_url=$( ruby -e "'$1'.sub('https://','').split('/').tap { |s| GURL='git@'+s.first+':'+s.last+'.git' } ; puts GURL.sub('.git.git','.git') " )
echo Cloning from $git_url
git clone $git_url $name

