#!/usr/bin/env bash
set +x
name=$1
ts=$(perl -e "print time")

if [[ -z "$name" ]] ; then
  echo Using aut0 name
  name="auto"
fi

if [[ -z "$(echo $name | grep -E ".png$")" ]] ; then
  name="$name.png"
fi
name="$ts-$name"

file=~/Dropbox/Public/screens/$name

echo "Saving $file and uploading to dropbox" > /dev/stderr

gnome-screenshot -f $file -a
url=$(dropbox puburl $file 2>&1)
echo "URL: $url"
echo $url | xsel -ib
