#!/usr/bin/env bash
name=$1
ts=$(perl -e "print time")

if [[ -z "$name" ]] ; then
  echo Needs a file name!
  exit 1
fi

if [[ -z "$(echo $name | grep -E ".png$")" ]] ; then
  name="$name.png"
fi
name="$ts-$name"

file=~/Dropbox/Public/screens/$name

echo "Saving $file and uploading to dropbox" > /dev/stderr

gnome-screenshot -f $file -a
dropbox puburl $file
