#!/usr/bin/env bash

vagrant_command() {
  echo "> Vagrant $1"
  vagrant $1
}

if [[ -z "$(ssh-add -L | grep id_rsa)" ]] ; then
  ssh-add ~/.ssh/id_rsa
fi

cd ~/proj/dev-machine

if [[ $(vagrant status | grep -E "default.*(suspended|saved)" | head -1) ]]  ; then
  vagrant_command "resume"
elif [[ $( vagrant status | grep -E "default.*(aborted|halted)" | head -1)  ]] ; then
  vagrant_command "up"
fi

vagrant_command "ssh"
