#!/usr/bin/env bash

function repoUrl() {
  echo "https://github.com/$(git remote -v | grep origin | head -1 | cut -f2 -d:  | sed 's/.git.*//')/tree/$(git symbolic-ref HEAD 2>/dev/null | awk -F/ '{ print $3}')"
}


open "$(repoUrl)/$1#L$2-L$3"
