#!/usr/bin/env bash

if [[ "$1" == '-h' ]] ; then
  echo 'git browse  to open current branch on GitHub'
  echo 'git browse <file>
  - to open file on current branch on GitHub'
  echo 'git browse <file> <line start><line end>
  - to open file on current branch on GitHub and to point to a
    given line or range of lines'
  echo 'git browse -c <commit sha> - open given commit on github'
  echo 'Example:'
  echo '    git browse bins/git-browse 5 10
                - will open https://github.com/lukaszkorecki/dotfiles/tree/master/bins/git-browse#L5-L10'
  echo '    git browse -c $(git log --pretty=oneline | grep fix | cut -f 1 -d ' ' | head -1)
                - opens latest commit with 'fix' in commit message'
  exit 0
fi


function currentBranch() {
  git symbolic-ref HEAD | rev | cut -d/ -f 1 | rev
}
function getRepoRoot() {
  # git rev-parse --show-toplevel
  if [[ -z "$1" || "$1" == "." ]] ; then
    echo ""
  else
    git ls-tree $(currentBranch) --full-name $1 | awk '{ print $4 }'
  fi
}
function repoUrl() {
  echo "https://github.com/$(git remote -v | grep origin | head -1 | cut -f2 -d:  | sed 's/.git.*//')/tree/$(currentBranch)"
}

if [[ "$1" == "-c" && "$2" != "" ]] ; then

  url=$(repoUrl | sed "s/tree/commit/")/$2

else
  if [[ "$2" != "" ]] ; then
    l1="L$2"
  fi

  if [[ "$3" != "" ]]; then
    l2="-L$3"
  fi

  path=$(getRepoRoot "$1")
  url="$(repoUrl)/$path#$l1$l2"

fi

echo $url
(  uname | grep "Darwin" >/dev/null ) && open "$url"
(  uname | grep 'Linux' >/dev/null ) && xdg-open "$url"
