#!/usr/bin/env bash

function repoUrl() {
  echo "https://github.com/$(git remote -v | grep origin | head -1 | cut -f2 -d:  | sed 's/.git.*//')/tree/$(git symbolic-ref HEAD 2>/dev/null | awk -F/ '{ print $3}')"
}

if [[ "$2" ]] ; then
  l1="L$2"
fi

if [[ "$3" ]]; then
  l2="-L$3"
fi

open "$(repoUrl)/$1#$l1$l2"
