#!/usr/bin/env bash
if [[ $1 == "-h" ]] ; then
echo "Usage:"
 echo "cd to a repo "
 echo "open-on-gh -o/-x <optional path to file or dir> "
 echo "-o - open in browser "
 echo "-x - just show the url "

exit 0
fi

current_branch=$(git symbolic-ref HEAD 2>/dev/null | awk -F/ '{ print $3}')
gh_url=$(git remote -v | grep origin | head -1 | cut -f2 -d:  | sed "s/.git.*//")

full_url="https://github.com/$gh_url/tree/$current_branch/$2"
if [[ $1 == "-o" ]] ; then
  open $full_url
else
  echo $full_url
fi
