#!/usr/bin/env bash
current_branch=$(git symbolic-ref HEAD 2>/dev/null | awk -F/ '{ print $3}')
gh_url=$(git remote -v | grep origin | head -1 | cut -f2 -d:  | sed "s/.git.*//")

full_url="https://github.com/$gh_url/tree/$current_branch/$1"
if [[ $2 == "-o" ]] ; then
  open $full_url
fi
