#!/usr/bin/env bash

# set -e

# Create new split panes in tmux window based on procfile
tmux_cmd() {
    local name="$1"
    local cmd="$2"

    echo "Launching $name with $cmd"
    if [[ "$cmd" != "" ]]; then
        echo tmux split-window -c . -h "'$cmd || bash'"
        tmux split-window "'$cmd || bash'"
    fi
}


parse_procfile_line() {
    local line="$1"
    local name="$(echo $line | cut -d: -f1 )"
    local cmd="$(echo $line | cut -d: -f2- )"

    tmux_cmd "$name" "$cmd"
}

read_proc_file() {
    local file="$1"
    while IFS='' read -r line || [[ -n "$line" ]] ; do
        parse_procfile_line "$line"
    done < "$file"
}

main() {
    local file="$1"
    read_proc_file $file
}


main ${1:-./Procfile}
