#!/usr/bin/env bash

file="$*"
vim -E  \
  -c "let g:html_no_progress=1" \
  -c "let g:html_number_lines=0" \
  -c "colorscheme Tomorrow" \
  -c ":TOhtml" \
  -cwqa $file

sed -i -e "s/monospace;/Monaco; font-size: 28pt;/g" "$file"".html"
