#!/usr/bin/env bash

mode=$1

name=docker-tmp-graphite

if [[ "$mode" = "start" ]] ; then
  docker run \
       --name $name \
       --detach \
       --publish=3003:80 \
       --publish=3004:81 \
       --publish=8125:8125/udp \
       --publish=8126:8126 \
       kamon/grafana_graphite
  exit $?
fi

if [[ "$mode" = "resume" ]] ; then
  docker start $name
  exit $?
fi

if [[ "$mode" = "stop" ]] ; then
  docker stop $name
  exit $?
fi


echo "commands: start / resume / stop"
