#!/usr/bin/env bash

list=$( tmux -2 -u ls)
if [ $? -eq 1 ]; then # no active sessions
  echo "No active sessions!, statrting a new one"
  tmux -2 -u
else
  session=$(echo $list | grep attached | cut -d : -f 1)
  echo "Joining Session: $session"
  tmux -2 -u new-session -t $session
fi
