#!/usr/bin/env bash
# sends an email-notification to flowdock
# ~/.fdaddr needs to have a valid flow address, one address per line
# like: <flow_name>@<domain>.flowdock.com
fd_addresses=$(cat ~/.fdaddr)
if [ -z "$fd_addresses" ]; then
  echo "No address in ~/.fdaddr"
  exit 1
fi

if [ -z "$1$2" ]; then
  echo "usage: fd-addr 'topic' 'message'"
  exit 1
fi

for addr in $(echo $fd_addresses | tr "\n" " "); do
  echo "$1" | mail -s "$2" -F $addr
done
