#!/usr/bin/env bash
echo "Logging to DEV VM"

location="$1"
user="$2"

if [ -z "$location" ] ; then
  location="~/Dev/dev-machine"
fi


if [ -z "$user" ] ; then
  user="vagrant"
fi

source ~/.DotFiles/bashrc
ssh-add ~/.vagrant.d/insecure_private_key
cd $location
vagrant up
ssh-add -l
ssh -A $user@192.168.33.10
