#!/usr/bin/env bash
if [[ $1 == '-h' ]]; then
  echo "Launches vim, opens a tmux pane and opens a split with guard"
  echo "workit <file/location to edit in vim>"
  exit 0
fi
tmux split-window -h -p 30 "cd $(pwd) ;  bundle exec guard || sleep 10" &
tmux select-pane -t 1
vim $1
